version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/bonus/nginx
    ports:
      - '443:443'
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - redis
      - ftp
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/bonus/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/bonus/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - inception
  
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
      - '6379:6379'
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception
  
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    ports:
      - '9876-9976:9876-9976'
      - '20:20'
      - '21:21'
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/touteiro/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/touteiro/data/mysql
      o: bind
