version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx_c
    ports:
      - '80:80'
      - '443:443'
    restart: always
    # environment:
    #   - NGINX_HOST=test.com
    #   - NGINX_PORT=80
  wordpress:
    build: ./wordpress
    container_name: wp_c
    ports:
      - '80:80'
    command: systemctl start nginx.service;systemctl enable nginx.service;