version: '2.18.1'
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '8080:8080'