FROM debian:11

RUN apt update && apt upgrade

RUN apt install -y php \
        php-bcmath \
        php-curl \
        php-imagick \
        php-intl \
        php-json \
        php-mbstring \
        php-mysql \
        php-xml \
        php-zip \
        systemctl

RUN apt install -y wordpress



